SELECT SUM(CAST(WatchID AS DOUBLE)), MIN(WatchID), MAX(WatchID), COUNT(WatchID), COUNT(DISTINCT WatchID) FROM hits;
SELECT SUM(CAST(JavaEnable AS DOUBLE)), MIN(JavaEnable), MAX(JavaEnable), COUNT(JavaEnable), COUNT(DISTINCT JavaEnable) FROM hits;
SELECT SUM(STRLEN(Title)), MIN(Title), MAX(Title), COUNT(Title), COUNT(DISTINCT Title) FROM hits;
SELECT SUM(CAST(GoodEvent AS DOUBLE)), MIN(GoodEvent), MAX(GoodEvent), COUNT(GoodEvent), COUNT(DISTINCT GoodEvent) FROM hits;
SELECT SUM(CAST(EPOCH(EventTime) AS DOUBLE)), MIN(EventTime), MAX(EventTime), COUNT(EventTime), COUNT(DISTINCT EventTime) FROM hits;
SELECT SUM(CAST((EventDate - DATE '1970-01-01') AS DOUBLE)), MIN(EventDate), MAX(EventDate), COUNT(EventDate), COUNT(DISTINCT EventDate) FROM hits;
SELECT SUM(CAST(CounterID AS DOUBLE)), MIN(CounterID), MAX(CounterID), COUNT(CounterID), COUNT(DISTINCT CounterID) FROM hits;
SELECT SUM(CAST(ClientIP AS DOUBLE)), MIN(ClientIP), MAX(ClientIP), COUNT(ClientIP), COUNT(DISTINCT ClientIP) FROM hits;
SELECT SUM(CAST(RegionID AS DOUBLE)), MIN(RegionID), MAX(RegionID), COUNT(RegionID), COUNT(DISTINCT RegionID) FROM hits;
SELECT SUM(CAST(UserID AS DOUBLE)), MIN(UserID), MAX(UserID), COUNT(UserID), COUNT(DISTINCT UserID) FROM hits;
SELECT SUM(CAST(CounterClass AS DOUBLE)), MIN(CounterClass), MAX(CounterClass), COUNT(CounterClass), COUNT(DISTINCT CounterClass) FROM hits;
SELECT SUM(CAST(OS AS DOUBLE)), MIN(OS), MAX(OS), COUNT(OS), COUNT(DISTINCT OS) FROM hits;
SELECT SUM(CAST(UserAgent AS DOUBLE)), MIN(UserAgent), MAX(UserAgent), COUNT(UserAgent), COUNT(DISTINCT UserAgent) FROM hits;
SELECT SUM(STRLEN(URL)), MIN(URL), MAX(URL), COUNT(URL), COUNT(DISTINCT URL) FROM hits;
SELECT SUM(STRLEN(Referer)), MIN(Referer), MAX(Referer), COUNT(Referer), COUNT(DISTINCT Referer) FROM hits;
SELECT SUM(CAST(IsRefresh AS DOUBLE)), MIN(IsRefresh), MAX(IsRefresh), COUNT(IsRefresh), COUNT(DISTINCT IsRefresh) FROM hits;
SELECT SUM(CAST(RefererCategoryID AS DOUBLE)), MIN(RefererCategoryID), MAX(RefererCategoryID), COUNT(RefererCategoryID), COUNT(DISTINCT RefererCategoryID) FROM hits;
SELECT SUM(CAST(RefererRegionID AS DOUBLE)), MIN(RefererRegionID), MAX(RefererRegionID), COUNT(RefererRegionID), COUNT(DISTINCT RefererRegionID) FROM hits;
SELECT SUM(CAST(URLCategoryID AS DOUBLE)), MIN(URLCategoryID), MAX(URLCategoryID), COUNT(URLCategoryID), COUNT(DISTINCT URLCategoryID) FROM hits;
SELECT SUM(CAST(URLRegionID AS DOUBLE)), MIN(URLRegionID), MAX(URLRegionID), COUNT(URLRegionID), COUNT(DISTINCT URLRegionID) FROM hits;
SELECT SUM(CAST(ResolutionWidth AS DOUBLE)), MIN(ResolutionWidth), MAX(ResolutionWidth), COUNT(ResolutionWidth), COUNT(DISTINCT ResolutionWidth) FROM hits;
SELECT SUM(CAST(ResolutionHeight AS DOUBLE)), MIN(ResolutionHeight), MAX(ResolutionHeight), COUNT(ResolutionHeight), COUNT(DISTINCT ResolutionHeight) FROM hits;
SELECT SUM(CAST(ResolutionDepth AS DOUBLE)), MIN(ResolutionDepth), MAX(ResolutionDepth), COUNT(ResolutionDepth), COUNT(DISTINCT ResolutionDepth) FROM hits;
SELECT SUM(CAST(FlashMajor AS DOUBLE)), MIN(FlashMajor), MAX(FlashMajor), COUNT(FlashMajor), COUNT(DISTINCT FlashMajor) FROM hits;
SELECT SUM(CAST(FlashMinor AS DOUBLE)), MIN(FlashMinor), MAX(FlashMinor), COUNT(FlashMinor), COUNT(DISTINCT FlashMinor) FROM hits;
SELECT SUM(STRLEN(FlashMinor2)), MIN(FlashMinor2), MAX(FlashMinor2), COUNT(FlashMinor2), COUNT(DISTINCT FlashMinor2) FROM hits;
SELECT SUM(CAST(NetMajor AS DOUBLE)), MIN(NetMajor), MAX(NetMajor), COUNT(NetMajor), COUNT(DISTINCT NetMajor) FROM hits;
SELECT SUM(CAST(NetMinor AS DOUBLE)), MIN(NetMinor), MAX(NetMinor), COUNT(NetMinor), COUNT(DISTINCT NetMinor) FROM hits;
SELECT SUM(CAST(UserAgentMajor AS DOUBLE)), MIN(UserAgentMajor), MAX(UserAgentMajor), COUNT(UserAgentMajor), COUNT(DISTINCT UserAgentMajor) FROM hits;
SELECT SUM(STRLEN(UserAgentMinor)), MIN(UserAgentMinor), MAX(UserAgentMinor), COUNT(UserAgentMinor), COUNT(DISTINCT UserAgentMinor) FROM hits;
SELECT SUM(CAST(CookieEnable AS DOUBLE)), MIN(CookieEnable), MAX(CookieEnable), COUNT(CookieEnable), COUNT(DISTINCT CookieEnable) FROM hits;
SELECT SUM(CAST(JavascriptEnable AS DOUBLE)), MIN(JavascriptEnable), MAX(JavascriptEnable), COUNT(JavascriptEnable), COUNT(DISTINCT JavascriptEnable) FROM hits;
SELECT SUM(CAST(IsMobile AS DOUBLE)), MIN(IsMobile), MAX(IsMobile), COUNT(IsMobile), COUNT(DISTINCT IsMobile) FROM hits;
SELECT SUM(CAST(MobilePhone AS DOUBLE)), MIN(MobilePhone), MAX(MobilePhone), COUNT(MobilePhone), COUNT(DISTINCT MobilePhone) FROM hits;
SELECT SUM(STRLEN(MobilePhoneModel)), MIN(MobilePhoneModel), MAX(MobilePhoneModel), COUNT(MobilePhoneModel), COUNT(DISTINCT MobilePhoneModel) FROM hits;
SELECT SUM(STRLEN(Params)), MIN(Params), MAX(Params), COUNT(Params), COUNT(DISTINCT Params) FROM hits;
SELECT SUM(CAST(IPNetworkID AS DOUBLE)), MIN(IPNetworkID), MAX(IPNetworkID), COUNT(IPNetworkID), COUNT(DISTINCT IPNetworkID) FROM hits;
SELECT SUM(CAST(TraficSourceID AS DOUBLE)), MIN(TraficSourceID), MAX(TraficSourceID), COUNT(TraficSourceID), COUNT(DISTINCT TraficSourceID) FROM hits;
SELECT SUM(CAST(SearchEngineID AS DOUBLE)), MIN(SearchEngineID), MAX(SearchEngineID), COUNT(SearchEngineID), COUNT(DISTINCT SearchEngineID) FROM hits;
SELECT SUM(STRLEN(SearchPhrase)), MIN(SearchPhrase), MAX(SearchPhrase), COUNT(SearchPhrase), COUNT(DISTINCT SearchPhrase) FROM hits;
SELECT SUM(CAST(AdvEngineID AS DOUBLE)), MIN(AdvEngineID), MAX(AdvEngineID), COUNT(AdvEngineID), COUNT(DISTINCT AdvEngineID) FROM hits;
SELECT SUM(CAST(IsArtifical AS DOUBLE)), MIN(IsArtifical), MAX(IsArtifical), COUNT(IsArtifical), COUNT(DISTINCT IsArtifical) FROM hits;
SELECT SUM(CAST(WindowClientWidth AS DOUBLE)), MIN(WindowClientWidth), MAX(WindowClientWidth), COUNT(WindowClientWidth), COUNT(DISTINCT WindowClientWidth) FROM hits;
SELECT SUM(CAST(WindowClientHeight AS DOUBLE)), MIN(WindowClientHeight), MAX(WindowClientHeight), COUNT(WindowClientHeight), COUNT(DISTINCT WindowClientHeight) FROM hits;
SELECT SUM(CAST(ClientTimeZone AS DOUBLE)), MIN(ClientTimeZone), MAX(ClientTimeZone), COUNT(ClientTimeZone), COUNT(DISTINCT ClientTimeZone) FROM hits;
SELECT SUM(CAST(EPOCH(ClientEventTime) AS DOUBLE)), MIN(ClientEventTime), MAX(ClientEventTime), COUNT(ClientEventTime), COUNT(DISTINCT ClientEventTime) FROM hits;
SELECT SUM(CAST(SilverlightVersion1 AS DOUBLE)), MIN(SilverlightVersion1), MAX(SilverlightVersion1), COUNT(SilverlightVersion1), COUNT(DISTINCT SilverlightVersion1) FROM hits;
SELECT SUM(CAST(SilverlightVersion2 AS DOUBLE)), MIN(SilverlightVersion2), MAX(SilverlightVersion2), COUNT(SilverlightVersion2), COUNT(DISTINCT SilverlightVersion2) FROM hits;
SELECT SUM(CAST(SilverlightVersion3 AS DOUBLE)), MIN(SilverlightVersion3), MAX(SilverlightVersion3), COUNT(SilverlightVersion3), COUNT(DISTINCT SilverlightVersion3) FROM hits;
SELECT SUM(CAST(SilverlightVersion4 AS DOUBLE)), MIN(SilverlightVersion4), MAX(SilverlightVersion4), COUNT(SilverlightVersion4), COUNT(DISTINCT SilverlightVersion4) FROM hits;
SELECT SUM(STRLEN(PageCharset)), MIN(PageCharset), MAX(PageCharset), COUNT(PageCharset), COUNT(DISTINCT PageCharset) FROM hits;
SELECT SUM(CAST(CodeVersion AS DOUBLE)), MIN(CodeVersion), MAX(CodeVersion), COUNT(CodeVersion), COUNT(DISTINCT CodeVersion) FROM hits;
SELECT SUM(CAST(IsLink AS DOUBLE)), MIN(IsLink), MAX(IsLink), COUNT(IsLink), COUNT(DISTINCT IsLink) FROM hits;
SELECT SUM(CAST(IsDownload AS DOUBLE)), MIN(IsDownload), MAX(IsDownload), COUNT(IsDownload), COUNT(DISTINCT IsDownload) FROM hits;
SELECT SUM(CAST(IsNotBounce AS DOUBLE)), MIN(IsNotBounce), MAX(IsNotBounce), COUNT(IsNotBounce), COUNT(DISTINCT IsNotBounce) FROM hits;
SELECT SUM(CAST(FUniqID AS DOUBLE)), MIN(FUniqID), MAX(FUniqID), COUNT(FUniqID), COUNT(DISTINCT FUniqID) FROM hits;
SELECT SUM(STRLEN(OriginalURL)), MIN(OriginalURL), MAX(OriginalURL), COUNT(OriginalURL), COUNT(DISTINCT OriginalURL) FROM hits;
SELECT SUM(CAST(HID AS DOUBLE)), MIN(HID), MAX(HID), COUNT(HID), COUNT(DISTINCT HID) FROM hits;
SELECT SUM(CAST(IsOldCounter AS DOUBLE)), MIN(IsOldCounter), MAX(IsOldCounter), COUNT(IsOldCounter), COUNT(DISTINCT IsOldCounter) FROM hits;
SELECT SUM(CAST(IsEvent AS DOUBLE)), MIN(IsEvent), MAX(IsEvent), COUNT(IsEvent), COUNT(DISTINCT IsEvent) FROM hits;
SELECT SUM(CAST(IsParameter AS DOUBLE)), MIN(IsParameter), MAX(IsParameter), COUNT(IsParameter), COUNT(DISTINCT IsParameter) FROM hits;
SELECT SUM(CAST(DontCountHits AS DOUBLE)), MIN(DontCountHits), MAX(DontCountHits), COUNT(DontCountHits), COUNT(DISTINCT DontCountHits) FROM hits;
SELECT SUM(CAST(WithHash AS DOUBLE)), MIN(WithHash), MAX(WithHash), COUNT(WithHash), COUNT(DISTINCT WithHash) FROM hits;
SELECT SUM(STRLEN(HitColor)), MIN(HitColor), MAX(HitColor), COUNT(HitColor), COUNT(DISTINCT HitColor) FROM hits;
SELECT SUM(CAST(EPOCH(LocalEventTime) AS DOUBLE)), MIN(LocalEventTime), MAX(LocalEventTime), COUNT(LocalEventTime), COUNT(DISTINCT LocalEventTime) FROM hits;
SELECT SUM(CAST(Age AS DOUBLE)), MIN(Age), MAX(Age), COUNT(Age), COUNT(DISTINCT Age) FROM hits;
SELECT SUM(CAST(Sex AS DOUBLE)), MIN(Sex), MAX(Sex), COUNT(Sex), COUNT(DISTINCT Sex) FROM hits;
SELECT SUM(CAST(Income AS DOUBLE)), MIN(Income), MAX(Income), COUNT(Income), COUNT(DISTINCT Income) FROM hits;
SELECT SUM(CAST(Interests AS DOUBLE)), MIN(Interests), MAX(Interests), COUNT(Interests), COUNT(DISTINCT Interests) FROM hits;
SELECT SUM(CAST(Robotness AS DOUBLE)), MIN(Robotness), MAX(Robotness), COUNT(Robotness), COUNT(DISTINCT Robotness) FROM hits;
SELECT SUM(CAST(RemoteIP AS DOUBLE)), MIN(RemoteIP), MAX(RemoteIP), COUNT(RemoteIP), COUNT(DISTINCT RemoteIP) FROM hits;
SELECT SUM(CAST(WindowName AS DOUBLE)), MIN(WindowName), MAX(WindowName), COUNT(WindowName), COUNT(DISTINCT WindowName) FROM hits;
SELECT SUM(CAST(OpenerName AS DOUBLE)), MIN(OpenerName), MAX(OpenerName), COUNT(OpenerName), COUNT(DISTINCT OpenerName) FROM hits;
SELECT SUM(CAST(HistoryLength AS DOUBLE)), MIN(HistoryLength), MAX(HistoryLength), COUNT(HistoryLength), COUNT(DISTINCT HistoryLength) FROM hits;
SELECT SUM(STRLEN(BrowserLanguage)), MIN(BrowserLanguage), MAX(BrowserLanguage), COUNT(BrowserLanguage), COUNT(DISTINCT BrowserLanguage) FROM hits;
SELECT SUM(STRLEN(BrowserCountry)), MIN(BrowserCountry), MAX(BrowserCountry), COUNT(BrowserCountry), COUNT(DISTINCT BrowserCountry) FROM hits;
SELECT SUM(STRLEN(SocialNetwork)), MIN(SocialNetwork), MAX(SocialNetwork), COUNT(SocialNetwork), COUNT(DISTINCT SocialNetwork) FROM hits;
SELECT SUM(STRLEN(SocialAction)), MIN(SocialAction), MAX(SocialAction), COUNT(SocialAction), COUNT(DISTINCT SocialAction) FROM hits;
SELECT SUM(CAST(HTTPError AS DOUBLE)), MIN(HTTPError), MAX(HTTPError), COUNT(HTTPError), COUNT(DISTINCT HTTPError) FROM hits;
SELECT SUM(CAST(SendTiming AS DOUBLE)), MIN(SendTiming), MAX(SendTiming), COUNT(SendTiming), COUNT(DISTINCT SendTiming) FROM hits;
SELECT SUM(CAST(DNSTiming AS DOUBLE)), MIN(DNSTiming), MAX(DNSTiming), COUNT(DNSTiming), COUNT(DISTINCT DNSTiming) FROM hits;
SELECT SUM(CAST(ConnectTiming AS DOUBLE)), MIN(ConnectTiming), MAX(ConnectTiming), COUNT(ConnectTiming), COUNT(DISTINCT ConnectTiming) FROM hits;
SELECT SUM(CAST(ResponseStartTiming AS DOUBLE)), MIN(ResponseStartTiming), MAX(ResponseStartTiming), COUNT(ResponseStartTiming), COUNT(DISTINCT ResponseStartTiming) FROM hits;
SELECT SUM(CAST(ResponseEndTiming AS DOUBLE)), MIN(ResponseEndTiming), MAX(ResponseEndTiming), COUNT(ResponseEndTiming), COUNT(DISTINCT ResponseEndTiming) FROM hits;
SELECT SUM(CAST(FetchTiming AS DOUBLE)), MIN(FetchTiming), MAX(FetchTiming), COUNT(FetchTiming), COUNT(DISTINCT FetchTiming) FROM hits;
SELECT SUM(CAST(SocialSourceNetworkID AS DOUBLE)), MIN(SocialSourceNetworkID), MAX(SocialSourceNetworkID), COUNT(SocialSourceNetworkID), COUNT(DISTINCT SocialSourceNetworkID) FROM hits;
SELECT SUM(STRLEN(SocialSourcePage)), MIN(SocialSourcePage), MAX(SocialSourcePage), COUNT(SocialSourcePage), COUNT(DISTINCT SocialSourcePage) FROM hits;
SELECT SUM(CAST(ParamPrice AS DOUBLE)), MIN(ParamPrice), MAX(ParamPrice), COUNT(ParamPrice), COUNT(DISTINCT ParamPrice) FROM hits;
SELECT SUM(STRLEN(ParamOrderID)), MIN(ParamOrderID), MAX(ParamOrderID), COUNT(ParamOrderID), COUNT(DISTINCT ParamOrderID) FROM hits;
SELECT SUM(STRLEN(ParamCurrency)), MIN(ParamCurrency), MAX(ParamCurrency), COUNT(ParamCurrency), COUNT(DISTINCT ParamCurrency) FROM hits;
SELECT SUM(CAST(ParamCurrencyID AS DOUBLE)), MIN(ParamCurrencyID), MAX(ParamCurrencyID), COUNT(ParamCurrencyID), COUNT(DISTINCT ParamCurrencyID) FROM hits;
SELECT SUM(STRLEN(OpenstatServiceName)), MIN(OpenstatServiceName), MAX(OpenstatServiceName), COUNT(OpenstatServiceName), COUNT(DISTINCT OpenstatServiceName) FROM hits;
SELECT SUM(STRLEN(OpenstatCampaignID)), MIN(OpenstatCampaignID), MAX(OpenstatCampaignID), COUNT(OpenstatCampaignID), COUNT(DISTINCT OpenstatCampaignID) FROM hits;
SELECT SUM(STRLEN(OpenstatAdID)), MIN(OpenstatAdID), MAX(OpenstatAdID), COUNT(OpenstatAdID), COUNT(DISTINCT OpenstatAdID) FROM hits;
SELECT SUM(STRLEN(OpenstatSourceID)), MIN(OpenstatSourceID), MAX(OpenstatSourceID), COUNT(OpenstatSourceID), COUNT(DISTINCT OpenstatSourceID) FROM hits;
SELECT SUM(STRLEN(UTMSource)), MIN(UTMSource), MAX(UTMSource), COUNT(UTMSource), COUNT(DISTINCT UTMSource) FROM hits;
SELECT SUM(STRLEN(UTMMedium)), MIN(UTMMedium), MAX(UTMMedium), COUNT(UTMMedium), COUNT(DISTINCT UTMMedium) FROM hits;
SELECT SUM(STRLEN(UTMCampaign)), MIN(UTMCampaign), MAX(UTMCampaign), COUNT(UTMCampaign), COUNT(DISTINCT UTMCampaign) FROM hits;
SELECT SUM(STRLEN(UTMContent)), MIN(UTMContent), MAX(UTMContent), COUNT(UTMContent), COUNT(DISTINCT UTMContent) FROM hits;
SELECT SUM(STRLEN(UTMTerm)), MIN(UTMTerm), MAX(UTMTerm), COUNT(UTMTerm), COUNT(DISTINCT UTMTerm) FROM hits;
SELECT SUM(STRLEN(FromTag)), MIN(FromTag), MAX(FromTag), COUNT(FromTag), COUNT(DISTINCT FromTag) FROM hits;
SELECT SUM(CAST(HasGCLID AS DOUBLE)), MIN(HasGCLID), MAX(HasGCLID), COUNT(HasGCLID), COUNT(DISTINCT HasGCLID) FROM hits;
SELECT SUM(CAST(RefererHash AS DOUBLE)), MIN(RefererHash), MAX(RefererHash), COUNT(RefererHash), COUNT(DISTINCT RefererHash) FROM hits;
SELECT SUM(CAST(URLHash AS DOUBLE)), MIN(URLHash), MAX(URLHash), COUNT(URLHash), COUNT(DISTINCT URLHash) FROM hits;
SELECT SUM(CAST(CLID AS DOUBLE)), MIN(CLID), MAX(CLID), COUNT(CLID), COUNT(DISTINCT CLID) FROM hits;